/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_image_ImageInfo */

#ifndef _Included_com_jkqj_magick_image_ImageInfo
#define _Included_com_jkqj_magick_image_ImageInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_image_ImageInfo
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageInfo_init
  (JNIEnv *, jclass);

/*
 * Class:     com_jkqj_magick_image_ImageInfo
 * Method:    destroyHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_image_ImageInfo_destroyHandler
  (JNIEnv *, jclass, jlong);

/*
  * Class:     com_jkqj_magick_image_ImageInfo
  * Method:    quality
  * Signature: (JI)V
  */
 JNIEXPORT void JNICALL Java_com_jkqj_magick_image_ImageInfo_quality
   (JNIEnv *, jclass, jlong, jint);

 /*
  * Class:     com_jkqj_magick_image_ImageInfo
  * Method:    compression
  * Signature: (JI)V
  */
 JNIEXPORT void JNICALL Java_com_jkqj_magick_image_ImageInfo_compression
   (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jkqj_magick_image_ImageInfo
 * Method:    setMagick
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_image_ImageInfo_setMagick
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_jkqj_magick_image_ImageInfo
 * Method:    setFileName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_image_ImageInfo_setFileName
  (JNIEnv *, jclass, jlong, jstring);
  
#ifdef __cplusplus
}
#endif
#endif
