/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_support_PdfSupport */

#ifndef _Included_com_jkqj_magick_support_PdfSupport
#define _Included_com_jkqj_magick_support_PdfSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_support_PdfSupport
 * Method:    convertPdfToPng
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jkqj_magick_support_PdfSupport_convertPdfToPng
  (JNIEnv *, jclass, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
