/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_support_GifSupport */

#ifndef _Included_com_jkqj_magick_support_GifSupport
#define _Included_com_jkqj_magick_support_GifSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_support_GifSupport
 * Method:    scale
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jkqj_magick_support_GifSupport_scale
  (JNIEnv *, jclass, jstring, jstring, jint, jint);


/*
 * Class:     com_jkqj_magick_support_GifSupport
 * Method:    thumbnail
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jkqj_magick_support_GifSupport_thumbnail
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
