/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_draw_PrimitiveSupport */

#ifndef _Included_com_jkqj_magick_draw_PrimitiveSupport
#define _Included_com_jkqj_magick_draw_PrimitiveSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_draw_PrimitiveSupport
 * Method:    escapeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jkqj_magick_draw_PrimitiveSupport_escapeString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
