/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_draw_Color */

#ifndef _Included_com_jkqj_magick_draw_Color
#define _Included_com_jkqj_magick_draw_Color
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_draw_Color
 * Method:    getColorInfo
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_jkqj_magick_draw_Color_getColorInfo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
