/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_image_ImageTransform */

#ifndef _Included_com_jkqj_magick_image_ImageTransform
#define _Included_com_jkqj_magick_image_ImageTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    autoOrientImage
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_autoOrientImage
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    chopImage
 * Signature: (JJJII)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_chopImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    cropImage
 * Signature: (JJJII)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_cropImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    flipImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_flipImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    flopImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_flopImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    transposeImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_transposeImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    transverseImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_transverseImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jkqj_magick_image_ImageTransform
 * Method:    trimImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_image_ImageTransform_trimImage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
