/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_draw_DrawInfo */

#ifndef _Included_com_jkqj_magick_draw_DrawInfo
#define _Included_com_jkqj_magick_draw_DrawInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jkqj_magick_draw_DrawInfo_init
  (JNIEnv *, jclass);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setFont
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setFont
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setMetrics
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setMetrics
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setFamily
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setFamily
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setPointSize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setPointSize
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    annotation
 * Signature: (JDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_annotation
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jstring);


/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setFill
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setFill
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setStroke
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setStroke
  (JNIEnv *, jclass, jlong, jstring);


/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setPrimitive
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setPrimitive
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setGravity
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setGravity
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setAlign
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setAlign
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setViewBoxRectangle
 * Signature: (JJJII)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setViewBoxRectangle
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setStrokeWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setStrokeWidth
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setGeometry
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setGeometry
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_jkqj_magick_draw_DrawInfo
 * Method:    setEncoding
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_draw_DrawInfo_setEncoding
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
