/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "common.h"
/* Header for class com_jkqj_magick_BaseMagick */

#ifndef _Included_com_jkqj_magick_BaseMagick
#define _Included_com_jkqj_magick_BaseMagick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jkqj_magick_BaseMagick
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_BaseMagick_init
  (JNIEnv *, jclass);

/*
 * Class:     com_jkqj_magick_BaseMagick
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jkqj_magick_BaseMagick_clean
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
